### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by wildsurfer** [jwilder/docker-gen#219]
I have a Swarm cluster built with `docker-machine`. On a master node I have a `jwilder/nginx-proxy` container that is listening docker socket. This container has docker-gen inside.

I have a big issue -- docker-gen is randomly failing.

```
2016-10-12T13:31:20.612355172Z dockergen.1 | panic: send on closed channel
2016-10-12T13:31:20.612403474Z dockergen.1 | goroutine 11 [running]:
2016-10-12T13:31:20.612465914Z dockergen.1 | 0x26
2016-10-12T13:31:20.612488777Z dockergen.1 | /usr/local/go1.5.2/src/sync/waitgroup.go:126 +0xb4
2016-10-12T13:31:20.612616935Z dockergen.1 | 0x650
2016-10-12T13:31:20.612629135Z dockergen.1 | o:157 +0x60
2016-10-12T13:31:20.612655487Z dockergen.1 | 0xc82045c680, 0x72, 0x0, 0x0)
2016-10-12T13:31:20.612705147Z dockergen.1 | 0x0, 0x0)
2016-10-12T13:31:20.612727779Z dockergen.1 | net.(*conn).Read(0xc820026000, 0xc820112000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.612799649Z dockergen.1 | /usr/local/go1.5.2/src/net/net.go:172 +0xe4
2016-10-12T13:31:20.612822170Z dockergen.1 | , 0x0, 0x0)
2016-10-12T13:31:20.612882300Z dockergen.1 | 0xc8200f82c0, 0xc820188108, 0xc820484000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.612911525Z dockergen.1 | bufio.(*Reader).Peek(0xc820018480, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.612983846Z dockergen.1 | /usr/local/go1.5.2/src/bufio/bufio.go:132 +0xcc
2016-10-12T13:31:20.612995255Z dockergen.1 | github.com/jwilder/docker-gen.(*generator).generateFromEvents
2016-10-12T13:31:20.613063005Z dockergen.1 | github.com/jwilder/docker-gen.(*generator).generateFromSignals.func1(0xc82019b300)
2016-10-12T13:31:20.613080175Z dockergen.1 | 0x0, 0x18)
2016-10-12T13:31:20.613157355Z dockergen.1 | (0xc82001ff28)
2016-10-12T13:31:20.613179528Z dockergen.1 | 
2016-10-12T13:31:20.613261117Z dockergen.1 | /usr/local/go1.5.2/src/net/fd_unix.go:232 +0x23a
2016-10-12T13:31:20.613273103Z dockergen.1 | , 0xc82008f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.613328095Z dockergen.1 | 0x167
2016-10-12T13:31:20.613349964Z dockergen.1 | 328 +0x21a
2016-10-12T13:31:20.613425239Z dockergen.1 | 0x0)
2016-10-12T13:31:20.613442789Z dockergen.1 | )
2016-10-12T13:31:20.613521953Z dockergen.1 | /usr/local/go1.5.2/src/encoding/json/stream.go:152 +0x287
2016-10-12T13:31:20.613544354Z dockergen.1 |  +0x6c4
2016-10-12T13:31:20.613637242Z dockergen.1 | , 0xc820014150)
2016-10-12T13:31:20.613649287Z dockergen.1 | 
2016-10-12T13:31:20.613686767Z dockergen.1 | /usr/local/go1.5.2/src/net/net.go:172 +0xe4
2016-10-12T13:31:20.613708182Z dockergen.1 | (0xc8201a8240, 0x7f4bf3ab5000, 0xc8200f2008, 0x5, 0x0, 0x0)
2016-10-12T13:31:20.613781420Z dockergen.1 | :455 +0xcc
2016-10-12T13:31:20.613802834Z dockergen.1 | , 0x0, 0x0)
2016-10-12T13:31:20.613853137Z dockergen.1 | , 0x0, 0x0, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.613877256Z dockergen.1 | 0xc8200f15f0)
2016-10-12T13:31:20.613932962Z dockergen.1 | , 0xc8202f4600, 0x600, 0x600, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.614047749Z dockergen.1 | 0x600, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.614169964Z dockergen.1 | 284 +0x192
2016-10-12T13:31:20.614303514Z dockergen.1 | 0x2d1
2016-10-12T13:31:20.614384992Z dockergen.1 | 0x0, 0x0, 0x0)
2016-10-12T13:31:20.614505906Z dockergen.1 | t/fd_poll_runtime.go:73 +0x3a
2016-10-12T13:31:20.614585023Z dockergen.1 | al.readLine(0xc8201f6420, 0x0, 0x0, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.614718087Z dockergen.1 | n/stream.go:57 +0x159
2016-10-12T13:31:20.618291448Z dockergen.1 | net.runtime_pollWait(0x7f4bf3afa4d0, 0x72, 0xc820014150)
2016-10-12T13:31:20.618305982Z dockergen.1 | usr/local/go1.5.2/src/bufio/bufio.go:97 +0x1e9
2016-10-12T13:31:20.618310840Z dockergen.1 | , 0x0)
2016-10-12T13:31:20.618328468Z dockergen.1 | o1.5.2/src/net/fd_unix.go:232 +0x23a
2016-10-12T13:31:20.618333711Z dockergen.1 | ernal.(*chunkedReader).Read(0xc82025c360, 0xc820098400, 0x200, 0x200, 0x0, 0x0, 0x0)
2016-10-12T13:31:20.618337404Z dockergen.1 | ed by github.com/fsouza/go-dockerclient.(*Client).eventHijack
2016-10-12T13:31:20.618340999Z dockergen.1 | pto/tls/conn.go:673 +0xae
```

**Comment by JamBalaya56562** [comment]
This should be resolved by the event-loop rewrite. In the current generator the watcher channels are owned by a single fan-out goroutine that is the only sender and the only closer (each close is immediately followed by `return`), so a send-on-closed-channel can't occur, and go-dockerclient guards its own listener sends. The original Swarm / unstable-daemon path now goes through a clean teardown + reconnect instead. Likely safe to close.
